In [1]:
import numpy as np

In [5]:
# 基础
# np.array() 是一个方法，传入一个 list
arr=np.array([1,2,3],dtype=np.float64)
# dtype 用于指定元素的类型
print(arr)
print(arr.ndim) # ndim 是属性

[1. 2. 3.]
1


In [7]:
# copy
arr1=np.copy(arr)
# 新建一个arr1，它的内容从 arr copy 过来
print(arr1)

[1. 2. 3.]


In [16]:
# 预定义形状
# 全 0
arr=np.zeros((2,3),dtype=np.int64)
print(arr)
arr=np.zeros((2,)) # 创建的是一个一维的向量
print(arr)

[[0 0 0]
 [0 0 0]]
[0. 0.]


In [18]:
# 全 1
arr=np.ones((2,3))
print(arr)

[[1. 1. 1.]
 [1. 1. 1.]]


In [19]:
# 未初始化
arr=np.empty((4,2))
print(arr)

[[4.67296746e-307 1.69121096e-306]
 [1.37962728e-306 1.89146896e-307]
 [7.56571288e-307 3.11525958e-307]
 [1.24610723e-306 1.29061142e-306]]


In [21]:
# 填充
arr=np.full((4,2),fill_value=5)
print(arr)

[[5 5]
 [5 5]
 [5 5]
 [5 5]]


In [22]:
arr2=np.zeros_like(arr)
print(arr2)
# arr2 跟 arr 形状一样，但是用 0 填充

[[0 0]
 [0 0]
 [0 0]
 [0 0]]
