In [1]:
import numpy as np

In [7]:
# 等差数列
arr=np.arange(1,10) # [start,end) step
# 跟 python 里的 range 一样
print(arr)
arr=np.arange(1,10,3)
print(arr)

[1 2 3 4 5 6 7 8 9]
[1 4 7]


In [13]:
# 等间隔数列
arr=np.linspace(1,10,5,dtype=np.float64)
# l,r,份数：把 [l,r] 等分成多少份
print(arr)

[ 1.    3.25  5.5   7.75 10.  ]


In [23]:
# 对数间隔数列
# 也就是生成的数列对 base 取 log 后等间隔
arr=np.logspace(0,4,5,base=10,dtype=int)
# 把 0-4 分成 5 份：0，1，2，3，4
# 再对每个数取 base^x（相当于多了这个操作）
print(arr)

[    1    10   100  1000 10000]
