In [2]:
import numpy as np
from numpy.conftest import dtype

In [6]:
# 特殊矩阵的构造
# 单位矩阵
arr=np.eye(4,dtype=int)
print(arr)

[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]


In [13]:
# 对角矩阵
arr=np.diag([1,2,3,5])
print(arr)

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 5]]


In [16]:
# 随机数组的生成
# 生成 [0,1) 之间的随机浮点数（均匀分布）
arr=np.random.rand(2,3)
# 参数：行，列
print(arr)

[[0.70278281 0.26303548 0.05197099]
 [0.00718807 0.8465345  0.3225511 ]]


In [29]:
# 生成指定范围区间的随机浮点数
# [l,r) shape
arr=np.random.uniform(3,5,(2,3))
print(arr)

[[3.69398172 3.17396939 4.92035175]
 [3.29876341 4.69736392 3.9870596 ]]


In [32]:
# 生成指定范围区间的随机整数
# [l,r) shape
arr=np.random.randint(3,10,(2,3))
print(arr)

[[6 3 4]
 [4 8 6]]


In [55]:
# 生成随机数列（正态分布）
# 生成标准正态分布随机数（均值为0，方差为1）
# 两边概率小，中间概率大
arr=np.random.randn(2,3)
print(arr)

[[ 1.05848808  1.0069962   0.11666646]
 [-0.26269392 -0.36910612  0.14042876]]


In [73]:
# 设置随机种子
# 每次运行生成的都是一样的
np.random.seed(10)
arr=np.random.randint(1,10,(2,5))
print(arr)

[[5 1 2 1 2]
 [9 1 9 7 5]]
