In [27]:
import numpy as np

In [28]:
# python 里所有的区间都是左闭右开
# 一维数组相关
arr=np.random.randint(1,100,10)
# [l,r) shape：填一个10，就是一维
print(arr)

[18 64 58 51 30 65 45 34 98 42]


In [29]:
print(arr[5])
print(arr[:]) # 所有
print(arr[1:10:2]) # [1,4) step=2

65
[18 64 58 51 30 65 45 34 98 42]
[64 51 65 34 42]


In [30]:
print(arr[arr<=10])
# 布尔索引，利用条件取筛选
# 支持 & |
# 每个条件都要加括号
print(arr[(arr>=10)&(arr<=40)])

[]
[18 30 34]


In [31]:
# slice 进行切片
print(arr[slice(1,4,2)])
# [l,r) step

[64 51]


In [35]:
# 二维数组相关
arr=np.random.randint(1,100,(4,5))
print(arr)

[[83 12 68  7 16]
 [ 9 91 88 41 56]
 [89  9 72 54 77]
 [87 70 10 60 87]]


In [44]:
print(arr[1][2])
print(arr[1,2])
# 二维数组索引

88
88


In [50]:
print(arr[1,:])
print((arr[1,:]).ndim)
# 前面是行 [l,r)
# 后面是列 [l,r)
print(arr[1:2,:])
print((arr[1:2,:]).ndim)

[ 9 91 88 41 56]
1
[[ 9 91 88 41 56]]
2


In [52]:
print(arr[arr>50])
# 变成一维数组了，单纯把符合条件的挑出来

[83 68 91 88 56 89 72 54 77 87 70 60 87]


In [58]:
print(arr[1])
# 下面对第一行的数组操作即可
print((arr[1])[arr[1]>50])
# 只要第一行中 > 50 的
# 那我先切片出来，成一个一维的 ndarray
# 再用 bool 索引

[ 9 91 88 41 56]
[91 88 56]


In [61]:
# 获取列数据，变成一个一维数组给你了
print(arr[:,3])

[ 7 41 54 60]
