In [2]:
import numpy as np

In [3]:
# numpy中的数组不用编写循环即可执行批量运算，称之为矢量化运算。
# 大小相等的数组之间的任何算术运算都会将运算应用到元素级。

In [15]:
# 算术运算
# 形状一样，那么对应元素来做运算
a=np.array([1,2,3])
b=np.array([4,5,6])
print(a+b)
print(a-b)
print(a*b)
print(a+2)

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[3 4 5]


In [14]:
# python 里的 list 的相加是拼接
# list 不支持算数运算，只能拼接
c=[1,2,3]
d=[4,5,6]
print(c+d)

[1, 2, 3, 4, 5, 6]


In [20]:
a=np.array([[1,2,3],[4,5,6]])
b=np.array([[4,5,6],[7,8,9]])
print(a+b)
print(a-b)
print(a*b)

[[ 5  7  9]
 [11 13 15]]
[[-3 -3 -3]
 [-3 -3 -3]]
[[ 4 10 18]
 [28 40 54]]


In [21]:
# 数组与标量，也是作用到元素上
print(a+2)
print(a*2)

[[3 4 5]
 [6 7 8]]
[[ 2  4  6]
 [ 8 10 12]]


In [28]:
# 广播机制：针对不同形状数组
# 它允许在不同形状的数组之间进行元素级运算
# 要在每个维度，要么相同，要么有一个是 1
a=np.array([1,2,3])
# a 只有一维，但是去看成 1*3 的二维
b=np.array([[4],[5],[6]])
# b 二维，3*1
'''
a (扩充成 3*3)
1 2 3
1 2 3
1 2 3
b (扩充成 3*3)
4 4 4
5 5 5
6 6 6
'''
print(a+b)

[[5 6 7]
 [6 7 8]
 [7 8 9]]


In [31]:
# 规则3：如果俩个数组的形状在任何一个维度上都不匹配，并且没有任何一个维度大小等于1，那么会引发异常。
arr5 = np.array([1, 2, 3]) # 1*3
arr6 = np.array([4, 5]) # 1*2
# 在列上，不同，没有 1，所以不能广播
# result = arr5 + arr6
# print(result)

In [36]:
# 矩阵运算
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
b=np.array([[4,5,6],[7,8,9],[1,2,3]])
# 这个是对应元素相乘
print(a*b)
# 这个也是对应元素
print(np.multiply(a,b))

[[ 4 10 18]
 [28 40 54]
 [ 7 16 27]]
[[ 4 10 18]
 [28 40 54]
 [ 7 16 27]]


In [37]:
# 矩阵乘法
print(a@b)
print(np.dot(a,b))

[[ 21  27  33]
 [ 57  72  87]
 [ 93 117 141]]
[[ 21  27  33]
 [ 57  72  87]
 [ 93 117 141]]
