# 2、ndarray
## 2.2. ndarray
### 2.2.1 ndarray 的特性（多维性）

In [3]:
import numpy as np

In [8]:
arr=np.array(5) # 创建 0 维的 ndarray 数组
print(f"维度：{arr.ndim}")

维度0


In [11]:
arr=np.array([1,2,3]) # 多一对中括号，加一维
print(arr)
print(arr.ndim)

[1 2 3]
1


In [13]:
arr=np.array([[1,2,3],[4,5,6]]) # 创建一个矩阵，填入每一行
# 2*3 两行，三列
print(arr)
print(arr.ndim)

[[1 2 3]
 [4 5 6]]
2


#### 同质性：所有元素类型一致

In [16]:
arr=np.array([1,23,'hello'])
# 1,23 被转化成字符串了
print(arr)
print(arr.ndim)

['1' '23' 'hello']
1


In [18]:
arr=np.array([1,2.5])
# 把 1 转化成浮点数
# 如果数组中有小数，dtype 会自动变成 float64（避免精度丢失）
print(arr)

[1.  2.5]


### 2.2.2. ndarray 的属性

#### shape：输出数组的形状，多少行多少列

In [20]:
arr=np.array([[1,2,3],[4,5,6]]) # 创建一个矩阵，填入每一行
# 2*3 两行，三列
print(arr)
print(arr.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)


#### ndim：数组的维度

#### size： 数组中一共有多少个元素

#### dtype：数组元素的类型，int64（默认）
如果数组中有小数，dtype 会自动变成 float64（避免精度丢失）

### 2.2.3 ndarray 的创建